### ISSUE TITLE
camera intrinsics

### ISSUE THREAD

**Issue by leiyaocui** [notmahi/dobb-e#2]
Thanks for your awesome works! I am currently engaged in transforming the depth image into a 3D representation. However, I have not been able to locate the camera intrinsics in your dataset, HoNY. Could you provide them?

**Comment by HaoyiZhu** [comment]
Hi, have you solved the problem? Where are the camera intrinsics?

**Comment by leiyaocui** [comment]
Dear Haoyi Zhu,

Sorry for my late reply. I have got the camera intrinsics from the author
of dobb-e. But now, I have deleted it on my computer. So I think you can
send your request directly to that guy.

Have a nice day,

Leiyao Cui.
