### ISSUE TITLE
Are the OK-Robot videos staged with telerobotics?

### ISSUE THREAD

**Issue by tzakrajs** [notmahi/dobb-e#5]
Someone is clearly driving this robot in the top right behind the curtain of Oz. So much for autonomous...

Thanks Elon

https://youtu.be/G7SBA5roNhI?t=62

**Comment by notmahi** [comment]
That is a tripod in the corner, the person in the closet is recording the automated robot run.

The code for ok-robot is also public here: https://github.com/ok-robot/ok-robot
